### ISSUE TITLE
[Bug]: Cannot drag&drop text to move it around

### ISSUE THREAD

**Issue by jamesjimmy88** [Panchovix/stable-diffusion-webui-reForge#46]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Moving the text around inside the prompt box is not working.
Dragging from the prompt window to other parts of the window (for example the sampling method box) works normally; same for any text box in the settings page; I simply cannot drop the text in the prompt text box (same for the negative prompt, both in the txt2img and the img2img tabs).
Tested on a fresh installation, both on firefox and chrome. The issue isn't present on any other website.

### Steps to reproduce the problem

Select some text in the prompt window
Click on it and drag it to another position
Release the mouse button
Watch as nothing happens

### What should have happened?

The text should have moved. the mouse cursor even changes shape while the text gets dragged.

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Sysinfo

[sysinfo-2024-07-21-16-37.json](https://github.com/user-attachments/files/16325300/sysinfo-2024-07-21-16-37.json)

### Console logs

```Shell
venv "C:\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.20.1-v1.10.0RC-latest-565-g332a1c38
Commit hash: 332a1c389c015812b42e5aa48d517aa9fa775693
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Launching Web UI with arguments:
Total VRAM 8192 MB, total RAM 48994 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
2024-07-21 18:33:36.646913: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-21 18:33:37.145842: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Using pytorch cross attention
ControlNet preprocessor location: C:\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
Loading model yiffymix_v51SDXL.safetensors [7f8fff9014] (1 out of 1)
Loading weights [7f8fff9014] from C:\stable-diffusion-webui-reForge\models\Stable-diffusion\yiffymix_v51SDXL.safetensors
2024-07-21 18:33:41,688 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.1s (prepare environment: 5.3s, import torch: 2.4s, import gradio: 0.6s, setup paths: 2.3s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 2.1s, create ui: 0.4s, gradio launch: 0.4s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Loading VAE weights specified in settings: C:\stable-diffusion-webui-reForge\models\VAE\sdxl_fixFP16ErrorsSDXLLowerMemoryUse_v10.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7091.1904296875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3922.8357315063477
Moving model(s) has taken 0.50 seconds
Model loaded in 3.8s (load weights from disk: 0.3s, forge instantiate config: 0.1s, forge load real models: 2.6s, load VAE: 0.1s, calculate empty prompt: 0.7s).
WARNING: Ignoring invalid distribution -rotobuf (c:\stable-diffusion-webui-reforge\venv\lib\site-packages)
```

**Comment by Panchovix** [comment]
Hi there, if you go back to this commit https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/6021b91402b3f7a1bc003d5e8778ac38506056bd does it also happens?

`git checkout 6021b91`

Should work to go temporally to that commit, then

`git checkout main`

to return to latest commit

**Comment by Panchovix** [comment]
Okay I have pushed a commit that fixes this. 
https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/ca9e7580d1588ff3f92b79c948c27abe4d16b4a2
https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/a96201d317c8c3288f8e4ded65a3dbc1e5898513
If you find any issue, please tell me.

**Comment by jamesjimmy88** [comment]
Dang, you're fast. Anyway, that "fixed" the issue, however the text gets copied instead of just getting moved. Holding shift doesn't override this behavior.

**Comment by Panchovix** [comment]
> Dang, you're fast. Anyway, that "fixed" the issue, however the text gets copied instead of just getting moved. Holding shift doesn't override this behavior.

Okay just pushed another commit, but seems Shift is used by another process and couldn't actually let me move text while pressing it, so I changed to Control (left), let me know if you find a better button or if that's ok.

If not pressing L-Ctrl, it moves the text.
If pressing L-Ctrl,, copies the text.

This applies being in or not in the same field (not sure if that behavior is expected between different text fields)

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/19b5160a31b06c74251b9c68a8c2193bccadd75a
https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/4784784f204dbab1b6e9f492cd4681e267b630fd

**Comment by jamesjimmy88** [comment]
It's working perfectly now. By default shift is used to move (as an override, if needed) and ctrl is used to copy, which is exactly what's happening here. A big thank you for the fix!

**Comment by jamesjimmy88** [comment]
Hello. I just updated to the latest commit ([f1.0.1-v1.10.1RC-latest-666-gb75934c0) and the issue is back. Let me know if you need additional info.

**Comment by Panchovix** [comment]
Hi there. Thanks for the report. Do you mean moving or copying, or both are not working?

**Comment by jamesjimmy88** [comment]
Neither is working. Selecting text and dragging it doesn't do anything, even if I hold shift (to force move) or control (to force copy).
Like the last time this is limited to the positive/negative prompt fields.

**Comment by Panchovix** [comment]
Okay I pushed a new commit now, I think it's got bugged because we added scripts callback last time.

Tested just moving and it seems to work, and holding ctrl seems to copy.

**Comment by jamesjimmy88** [comment]
Just updated and everything is working perfectly. Thank you once again.

**Comment by Panchovix** [comment]
Nice!
